import type { ImageMetadata } from "astro";
import type { Story } from "..";
import thumbnail from "./thumbnail.jpg";
const importPromises = import.meta.glob("./image*.jpg");

async function image(index: number): Promise<ImageMetadata> {
  const paddedIndex = index.toString().padStart(3, "0");
  console.log({ index });
  const promise = importPromises[`./image${paddedIndex}.jpg`]!;
  const module = (await promise()) as any;
  return module.default as ImageMetadata;
}

const description = `
במרץ 2023 סיון ואורי טסו לסמסטר בברלין. אני הצטרפתי אליהם לחודש הראשון שהם היו שם (מרץ). מתישהו באמצע גם גלי באה ואז מתישהו באמצע עשיתי גם סיבוב בהולנד

<small>ואז אחרי שנה עברתי לברלין אופס</small>
`;

export const story: Story = {
  id: "berlin-netherlands-2023",
  title: "ברלין והולנד 2023",
  description,
  date: new Date("2023-03-02"),
  thumbnail,
  items: [
    {
      type: "image",
      src: await image(1),
    },

    { type: "image", src: await image(2) },
    { type: "image", src: await image(3) },
    { type: "image", src: await image(4) },
    { type: "image", src: await image(5) },
    { type: "image", src: await image(6) },
    { type: "image", src: await image(7) },
    { type: "image", src: await image(8) },
    { type: "image", src: await image(9) },
    { type: "image", src: await image(10) },
    { type: "image", src: await image(11) },
    { type: "image", src: await image(12) },
    { type: "image", src: await image(13) },
    { type: "image", src: await image(14) },
    { type: "image", src: await image(15) },
    { type: "image", src: await image(16) },
    { type: "image", src: await image(17) },
    { type: "image", src: await image(18) },
    { type: "image", src: await image(19) },
    { type: "image", src: await image(20) },
    { type: "image", src: await image(21) },
    { type: "image", src: await image(22) },
    { type: "image", src: await image(23) },
    { type: "image", src: await image(24) },
    { type: "image", src: await image(25) },
    { type: "image", src: await image(26) },
    { type: "image", src: await image(27) },
    { type: "image", src: await image(28) },
    { type: "image", src: await image(29) },
    { type: "image", src: await image(30) },
    { type: "image", src: await image(31) },
    { type: "image", src: await image(32) },
    { type: "image", src: await image(33) },
    { type: "image", src: await image(34) },
    { type: "image", src: await image(35) },
    { type: "image", src: await image(36) },
    { type: "image", src: await image(37) },
    { type: "image", src: await image(38) },
    { type: "image", src: await image(39) },
    { type: "image", src: await image(40) },
    { type: "image", src: await image(41) },
    { type: "image", src: await image(42) },
    { type: "image", src: await image(43) },
    { type: "image", src: await image(44) },
    { type: "image", src: await image(45) },
    { type: "image", src: await image(46) },
    { type: "image", src: await image(47) },
    { type: "image", src: await image(48) },
    { type: "image", src: await image(49) },
    { type: "image", src: await image(50) },
    { type: "image", src: await image(51) },
    { type: "image", src: await image(52) },
    { type: "image", src: await image(53) },
    { type: "image", src: await image(54) },
    { type: "image", src: await image(55) },
    { type: "image", src: await image(56) },
    { type: "image", src: await image(57) },
    { type: "image", src: await image(58) },
    { type: "image", src: await image(59) },
    { type: "image", src: await image(60) },
    { type: "image", src: await image(61) },
    { type: "image", src: await image(62) },
    { type: "image", src: await image(63) },
    { type: "image", src: await image(64) },
    { type: "image", src: await image(65) },
    { type: "image", src: await image(66) },
    { type: "image", src: await image(67) },
    { type: "image", src: await image(68) },
    { type: "image", src: await image(69) },
    { type: "image", src: await image(70) },
    { type: "image", src: await image(71) },
    { type: "image", src: await image(72) },
    { type: "image", src: await image(73) },
    { type: "image", src: await image(74) },
    { type: "image", src: await image(75) },
    { type: "image", src: await image(76) },
    { type: "image", src: await image(77) },
    { type: "image", src: await image(78) },
    { type: "image", src: await image(79) },
    { type: "image", src: await image(80) },
    { type: "image", src: await image(81) },
    { type: "image", src: await image(82) },
    { type: "image", src: await image(83) },
    { type: "image", src: await image(84) },
    { type: "image", src: await image(85) },
    { type: "image", src: await image(86) },
    { type: "image", src: await image(87) },
    { type: "image", src: await image(88) },
    { type: "image", src: await image(89) },
    { type: "image", src: await image(90) },
    { type: "image", src: await image(91) },
    { type: "image", src: await image(92) },
    { type: "image", src: await image(93) },
    { type: "image", src: await image(94) },
    { type: "image", src: await image(95) },
    { type: "image", src: await image(96) },
    { type: "image", src: await image(97) },
    { type: "image", src: await image(98) },
    { type: "image", src: await image(99) },
    { type: "image", src: await image(100) },
    { type: "image", src: await image(101) },
    { type: "image", src: await image(102) },
    { type: "image", src: await image(103) },
    { type: "image", src: await image(104) },
    { type: "image", src: await image(105) },
    { type: "image", src: await image(106) },
    { type: "image", src: await image(107) },
    { type: "image", src: await image(108) },
    { type: "image", src: await image(109) },
    { type: "image", src: await image(110) },
    { type: "image", src: await image(111) },
    { type: "image", src: await image(112) },
    { type: "image", src: await image(113) },
    { type: "image", src: await image(114) },
    { type: "image", src: await image(115) },
    { type: "image", src: await image(116) },
    { type: "image", src: await image(117) },
    { type: "image", src: await image(118) },
    { type: "image", src: await image(119) },
    { type: "image", src: await image(120) },
    { type: "image", src: await image(121) },
    { type: "image", src: await image(122) },
    { type: "image", src: await image(123) },
    { type: "image", src: await image(124) },
    { type: "image", src: await image(125) },
    { type: "image", src: await image(126) },
    { type: "image", src: await image(127) },
    { type: "image", src: await image(128) },
    { type: "image", src: await image(129) },
    { type: "image", src: await image(130) },
    { type: "image", src: await image(131) },
  ],
};
